add miner to mine the block
Encode-May-2022-Team-J/solidity-bootcamp-week2-project pull request #2
Opened 2022-05-29 15:20 UTC by JoshuaLim995

# 🐛 Bug Fix
Bug fix for Issue https://github.com/Encode-May-2022-Team-J/solidity-bootcamp-week2-project/issues/1#issue-1251913681

2022-05-29 15:22 UTC, eileenwong9305 commented on tests/customBallot/CustomBallotHomework.ts
> +            await ballotContract.deployed();
This line of code is duplicated in line 116

2022-05-29 15:25 UTC, eileenwong9305 commented on tests/customBallot/CustomBallotHomework.ts
> +        tokenContract = await tokenFactory.deploy()
Missing the line `await tokenContract.deployed();`

2022-05-29 15:25 UTC, eileenwong9305 requested changes
Missing line of code and duplicates of code found

2022-05-29 15:40 UTC, eileenwong9305 approved these changes

2022-05-30 10:21 UTC, tikisailor approved these changes

2022-05-30 13:21 UTC, merged